nowo_doctrine_deadlock_retry:
    default_profile: default
    profiles:
        default:
            max_retries: 3
            sleep_ms: 50
            rollback_on_deadlock: true
        batch:
            max_retries: 5
            sleep_ms: 200
            rollback_on_deadlock: true
