services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nowo\DoctrineDeadlockRetryBundle\Service\DeadlockRetryService:
    arguments:
      $profiles: []
      $defaultProfile: 'default'
